### ISSUE TITLE
GPSService.Instance is null

### ISSUE THREAD

**Issue by janusznoszczynski** [Xamarians/Xamarians.GPS#1]
Checked in Android and UWP projects

**Comment by Xamarians** [comment]
Hi janusznoszczynski,

It works fine at my end for android, did you call the Xamarians.GPS.Droid.GPSServiceAndroid.Initialize(this);
function in the MainActivity.cs?

Please go through the Readme once again.

**Comment by Xamarians** [comment]
Library only supports Android and iOS platforms and doesn't support Windows or UWP.
